export { default as Home } from './Home/HomePage';
export { Dictionary } from './Dictionary';
export { List } from './List';
export { Lists } from './Lists';
export { Movie } from './Movie';
export { MoviesAndTV } from './MoviesAndTV';
export { Quiz } from './Quiz';
export { Settings } from './Settings';
export { Subtitles } from './Subtitles';
export { VocabularyLevel } from './VocabularyLevel';
